http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: "/ip"
  mahasiswa:
    host: localhost
    paths: '/mahasiswa/*'
  jurusan:
    host: localhost
    paths: '/jurusan/*'
serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
  mahasiswaService:
    url: 'http://localhost:3000'
  jurusanService:
    url: 'http://localhost:3001'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  mahasiswaPipeline:
    apiEndpoints:
      - mahasiswa
    policies:
      - proxy:
          - action:
              serviceEndpoint: mahasiswaService
              changeOrigin: true
              stripPath:    true
  jurusanPipeline:
    apiEndpoints:
      - jurusan
    policies:
      - proxy:
          - action:
              serviceEndpoint: jurusanService
              changeOrigin: true
              stripPath:    true
  default:
    apiEndpoints:
      - api
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
